"""add_push_endpoint_to_devices

Revision ID: b830fa71e3a3
Revises: ec81cec02d0e
Create Date: 2026-08-30 16:52:57.032138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b830fa71e3a3'
down_revision: Union[str, Sequence[str], None] = 'ec81cec02d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('push_subscription_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('push_subscription_updated_at')
        batch_op.drop_column('push_subscription')

    # ### end Alembic commands ###
