"""add_clipboard_limit_to_users

Revision ID: ec81cec02d0e
Revises: 967bec859da9
Create Date: 2026-08-27 00:19:42.471367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec81cec02d0e'
down_revision: Union[str, Sequence[str], None] = '967bec859da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clipboard_limit', sa.Integer(), server_default='100', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('clipboard_limit')

    # ### end Alembic commands ###
